# There was a bug where the first test would be considered a
# 'lone not' failure.
print <<DUMMY;
ok 1
ok 2
ok 3
ok 4
1..4
DUMMY
